name: Publish
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kobonaut/elm-terminal
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}